

	.FUNCT	V-FLUSH
	EQUAL?	PRSO,INTNUM \?CND1
	EQUAL?	P-NUMBER,33 \?CND1
	GETB	0,18
	ZERO?	STACK /?THN6
	ZERO?	P-VMERGE /?CND1
?THN6:	CALL	GOTO,P-NMERGE
	CALL	V-LOOK
	RTRUE	
?CND1:	PRINTR	"You can't flush that."

	.ENDI
